# name:
# on:
# job:
#   check-bats-version:
#   run-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v3
#     - user: actions/setup-node@v3
#       with:
#         node-version: 14
#     - run: npm install
#     - run: npm install -g bats
#     - run: bats -v

name: Super-Linter

on: push

jobs:
  super-linter:
    name: Lint code bast
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      
      - name: Run Supser-Linter
      - uses: super-linter/action@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
